100 hooktrigger methods
hamal-io/hamal pull request #119
Opened 2023-11-25 20:30 UTC by jonsberg

2023-11-26 00:47 UTC, dominique-dymke requested changes

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/core/src/integrationTest/kotlin/io/hamal/core/req/handler/trigger/CreateTriggerHandlerTest.kt
> +        fun `Tries to create an invalid trigger`() {
This test name does not describe the problem case you want to test - as in: What is an invalid trigger in this case

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/api/src/integrationTest/kotlin/io/hamal/api/http/controller/trigger/TriggerCreateControllerTest.kt
> +
```suggestion

```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/api/src/integrationTest/kotlin/io/hamal/api/http/controller/trigger/TriggerCreateControllerTest.kt
> +        fun `Creates valid triggers`() {
A better test name would be great, which describes the why

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/api/src/integrationTest/kotlin/io/hamal/api/http/controller/trigger/TriggerCreateControllerTest.kt
> +        fun `Tries to create invalid trigger`() {
Same test name - what makes the trigger invalid

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/repository/sqlite/src/main/kotlin/io/hamal/repository/sqlite/record/trigger/Repository.kt
> +                }
Good idea - but this should be handled differently:

==> on sqlite level with an partial unique index

see ProjectionUniqueName as reference implementation

Do the same thing for Memory

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/repository/memory/src/main/kotlin/io/hamal/repository/memory/record/Trigger.kt
> +
see sqlite implementation comment

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/repository/testbed/src/test/kotlin/io/hamal/repository/TriggerTest.kt
> +        fun `Tries to register invalid hook triggers`() = runWith(TriggerRepository::class) {
what makes those hook trigger invalid?

2023-11-26 00:47 UTC, dominique-dymke commented on platform/backend/repository/testbed/src/test/kotlin/io/hamal/repository/TriggerTest.kt
> +        fun `Registers valid triggers`() = runWith(TriggerRepository::class) {
same test name

2023-11-26 00:47 UTC, dominique-dymke commented on platform/runner-plugin/std/sys/src/main/kotlin/io/hamal/plugin/std/sys/topic/trigger/TriggerCreateFunction.kt
> +                            else -> null
```
hookMethod = arg1.findString("hook_method")?.let(HookMethod::valueOf),
```

can be simplified as - we want to use the same Name in lua as in kotlin

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/create/create_invalid/01.lua
> +    hook_method = 'GET'
```suggestion
    hook_method = 'Get'
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/create/create_invalid/01.lua
> +    hook_method = 'GET'
```suggestion
    hook_method = 'Get'
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/create/current_flow/01.lua
> +    hook_method = 'GET',
```suggestion
    hook_method = 'Get',
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/create/different_flow/01.lua
> +    hook_method = 'GET',
```suggestion
    hook_method = 'Get',
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/list/01.lua
> +    hook_method = 'GET',
```suggestion
    hook_method = 'Get',
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/name_unique_in_flow/01.lua
> +    hook_method = 'GET'
```suggestion
    hook_method = 'Get'
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/name_unique_in_flow/01.lua
> +    hook_method = 'POST'
```suggestion
    hook_method = 'Post'
```

2023-11-26 00:47 UTC, dominique-dymke commented on platform/testbed/src/integrationTest/resources/api/trigger/hook/name_unique_in_flow/01.lua
> +    hook_method = 'PATCH'
```suggestion
    hook_method = 'Patch'
```

2023-11-28 19:56 UTC, jonsberg commented
- SQLite implementation --> ProjectionUniqueHook (separate table, unique constraints), so ProjectionCurrent is no longer bothered with this
- memory implementation --> MutableSet
- introduced a method ensureHookUnique to TriggerQueryRepo, that utilizes this Table/Set to ensure the client receives a BadRequest before the operation 
- if this is bs I'll remove it again

2023-12-02 12:44 UTC, dominique-dymke approved these changes
well done

2023-12-02 12:49 UTC, merged